### ISSUE TITLE
possible to add attributes to injected style tag?

### ISSUE THREAD

**Issue by redonkulus** [Anidetrix/rollup-plugin-styles#119]
I need to pass an `id` attribute to the injected `style` tag so that I can access the CSS later on. Is it possible to add this functionality? It could be generic and support any number of attribute via some object passed into inject options...

**Comment by Anidetrix** [comment]
Hello @redonkulus , thank you for your time and suggestion!

Just `id` seems very limiting to me, considering by default injector creates multiple `style` tags, which means they all will have the same `id`, which is generally not the best practice.

I propose the following:
- To set `id` attribute start selector with `#`
- To set `class` attribute start selector with `.`
- Otherwise sets `selector` data attribute

Please let me know if that will work for you.

**Comment by redonkulus** [comment]
That works for me as long as I can target a specific id for my usecase.

**Comment by Anidetrix** [comment]
I've generalized it even more, see [here](https://anidetrix.github.io/rollup-plugin-styles/interfaces/_index_d_.injectoptions.html#attributes). I hope this solves your problem!

**Comment by redonkulus** [comment]
@Anidetrix tried it locally and it works great! thanks for the quick turnaround, really helped me out.

**Comment by Anidetrix** [comment]
@redonkulus I'm glad, good luck with your work! Can I close this issue?
